plugins {
    java
}

group = "dev.magicnuke"
version = "1.0.0"
description = "Launchable 3D nukes with mushroom clouds, craters and a built-in resource pack."

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

// The resource pack lives in src/main/pack (generated by tools/generate_pack.py).
// It is zipped and embedded in the jar; the plugin hosts it for players itself.
val resourcePackZip = tasks.register<Zip>("resourcePackZip") {
    from("src/main/pack")
    archiveFileName.set("MagicNuke-ResourcePack.zip")
    destinationDirectory.set(layout.buildDirectory.dir("pack"))
    isPreserveFileTimestamps = false
    isReproducibleFileOrder = true
}

tasks {
    compileJava {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
    }

    processResources {
        filteringCharset = Charsets.UTF_8.name()
        val props = mapOf("version" to project.version, "description" to project.description)
        inputs.properties(props)
        filesMatching("plugin.yml") {
            expand(props)
        }
        from(resourcePackZip) {
            rename { "magicnuke-pack.zip" }
        }
    }

    jar {
        archiveFileName.set("MagicNuke-${project.version}.jar")
    }

    register<Copy>("dist") {
        description = "Copies the plugin jar and the standalone resource pack zip to build/dist."
        from(jar, resourcePackZip)
        into(layout.buildDirectory.dir("dist"))
    }

    build {
        dependsOn("dist")
    }
}
