#!/usr/bin/env python3
"""Writes docs/RESOURCE_PACK.md: the full pack folder layout (generated from the real files) and setup notes."""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import assets as A  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PACK = ROOT / 'resourcepack'
OUT = ROOT / 'docs' / 'RESOURCE_PACK.md'

SUFFIX = re.compile(r'^(?P<base>.+?)(?P<tier>_t[23]|_drained|_unlit)?(?P<glow>_glow)?(?P<pbr>_[ns])?\.png(?P<meta>\.mcmeta)?$')


def collapse_textures(files: list[str]) -> list[str]:
    """Groups echo_lens.png, echo_lens_n.png, echo_lens_t2_glow_s.png … into one line per asset."""
    groups = defaultdict(set)
    for f in files:
        m = SUFFIX.match(f)
        if not m:
            groups[f].add('')
            continue
        variant = (m['tier'] or '') + (m['glow'] or '') + (m['pbr'] or '') + ('.png' + (m['meta'] or ''))
        groups[m['base']].add(variant)
    out = []
    needles = sorted(b for b in groups if re.match(r'flare_compass_needle_\d+$', b))
    if needles:
        out.append(f'flare_compass_needle_00 … _{needles[-1][-2:]}  ×{len(groups[needles[0]])} each  '
                   f'({", ".join(sorted(groups[needles[0]]))})')
    for base in sorted(groups):
        if base in needles:
            continue
        vs = groups[base]
        out.append(f'{base}  ×{len(vs)}  ({", ".join(sorted(vs))[:120]}{"…" if len(", ".join(vs)) > 120 else ""})')
    return out


def tree(path: Path, prefix='') -> list[str]:
    lines = []
    entries = sorted(path.iterdir(), key=lambda p: (p.is_file(), p.name))
    dirs = [e for e in entries if e.is_dir()]
    files = [e.name for e in entries if e.is_file()]
    items = [(d.name + '/', d) for d in dirs]
    if path.name == 'item' and path.parent.name == 'textures':
        items += [(line, None) for line in collapse_textures(files)]
    elif len(files) > 12:
        stems = sorted({re.sub(r'_(t[23]|drained|unlit|needle_\d+)$', '', Path(f).stem) for f in files})
        variants = sorted({m.group(1) for f in files for m in [re.search(r'_(t[23]|drained|unlit|needle_\d+)\.json$', f)] if m})
        label = f'{len(files)} files (*.json'
        label += f'; variants: {", ".join(v if not v.startswith("needle") else "needle_00…15" for v in dict.fromkeys(variants))})' if variants else ')'
        items += [(label, None)]
        row = ''
        for stem in stems:
            if len(row) + len(stem) > 90:
                items.append(('    ' + row.rstrip(', '), None))
                row = ''
            row += stem + ', '
        if row:
            items.append(('    ' + row.rstrip(', '), None))
    else:
        items += [(f, None) for f in files]
    for i, (label, sub) in enumerate(items):
        last = i == len(items) - 1
        lines.append(prefix + ('└── ' if last else '├── ') + label)
        if sub is not None:
            lines += tree(sub, prefix + ('    ' if last else '│   '))
    return lines


def main():
    files = [p for p in PACK.rglob('*') if p.is_file()]
    size = sum(p.stat().st_size for p in files)
    sha_file = ROOT / 'build' / 'pack' / 'Shardwatch-pack.zip.sha1'
    sha = sha_file.read_text().strip() if sha_file.exists() else '<run ./gradlew :shardwatch:packZip>'
    lines = ['# Shardwatch resource pack', '',
             f'Generated by `tools/generate_pack.py`. {len(files)} files, {size / 1e6:.1f} MB unpacked. The zip built from this '
             f'commit has SHA-1 `{sha}`.', '',
             '## Folder layout', '', '```', 'resourcepack/'] + tree(PACK) + ['```', '',
             '`textures/item` lines group one asset: the base albedo, tier variants (`_t2`, `_t3`), states (`_drained`, `_unlit`), '
             'the animated emissive layer (`_glow` + `.mcmeta`) and LabPBR maps (`_n` normal, `_s` specular) for each.', '']
    lines += ['## What each part does', '',
              '| Path | Purpose |', '|---|---|',
              '| `pack.mcmeta` | Pack format 75 (Minecraft 1.21.11) via `min_format`/`max_format`. |',
              '| `assets/shardwatch/items/*.json` | Item model definitions referenced by the `item_model` component. Tiers use `select` on `custom_model_data` strings, the Timeglass uses `range_dispatch` on `cooldown`, the Veil Lantern a `condition` on a flag, the Flare Compass a `composite` with a 16-way `range_dispatch` on `compass`. |',
              '| `assets/shardwatch/models/item/*.json` | 3D relief models in Blockbench "Java Block/Item" format: per-pixel-run elements with real depth, emissive overlay planes (`light_emission: 15`), display angles for every slot. |',
              '| `assets/shardwatch/textures/item/` | 64×64 pixel art, emissive animation strips, LabPBR `_n`/`_s`. |',
              '| `assets/shardwatch/textures/gui/sprites/tooltip/` | The `shardwatch:crystal` tooltip style (nine-slice background + frame). |',
              '| `assets/shardwatch/textures/font/` + `font/gui.json` | Menu backgrounds drawn as font glyphs, plus negative-space glyphs to position them. |',
              '| `assets/shardwatch/font/sigils.json` | Chat sigils (rank and Keepsake glyphs). |',
              '| `assets/shardwatch/sounds.json` + `sounds/` | 32 synthesised sound events (mono Ogg Vorbis). |',
              '| `assets/shardwatch/lang/en_us.json` | Subtitles for every sound. |',
              '| `../blockbench/*.bbmodel` | Editable Blockbench projects for every model, textures embedded. |', '']
    lines += ['Nothing is placed under `assets/minecraft/`, so no vanilla item, sound, font or particle is replaced.', '',
              '## Assets', '', '| Asset | Kind | Stage | What it is |', '|---|---|---|---|']
    for a in A.ALL:
        lines.append(f'| `{a.id}` | {a.kind} | {a.stage} | {a.title} |')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(lines) + '\n')
    print(f'wrote {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
